import os
from PyQt5 import QtCore, QtGui, QtWidgets

#os.startfile(r'C:\Users\ДОМ\PycharmProjects\Клеточный автомат\Wild1.py')
class Ui_Title(object):
    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(320, 500)
        self.centralwidget = QtWidgets.QWidget(Title)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 320, 500))
        self.widget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.511364, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 82, 0, 255), stop:1 rgba(0, 0, 0, 255));")
        self.widget.setObjectName("widget")
        self.CRule = QtWidgets.QComboBox(self.widget)
        self.CRule.setGeometry(QtCore.QRect(169, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.CRule.setFont(font)
        self.CRule.setStyleSheet("color: rgb(224, 255, 220);\n"
                                 "background-color: rgb(91, 107, 88);")
        self.CRule.setFrame(False)
        self.CRule.setObjectName("CRule")
        self.CRule.addItem("")
        self.CRandom = QtWidgets.QCheckBox(self.widget)
        self.CRandom.setGeometry(QtCore.QRect(10, 50, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.CRandom.setFont(font)
        self.CRandom.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                                   "color: rgb(224, 255, 220);")
        self.CRandom.setTristate(False)
        self.CRandom.setObjectName("CRandom")
        self.LRule = QtWidgets.QLabel(self.widget)
        self.LRule.setGeometry(QtCore.QRect(10, 80, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LRule.setFont(font)
        self.LRule.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                                 "color: rgb(224, 255, 220);")
        self.LRule.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LRule.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LRule.setObjectName("LRule")
        self.PBL = QtWidgets.QPushButton(self.widget)
        self.PBL.setGeometry(QtCore.QRect(10, 10, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.PBL.setFont(font)
        self.PBL.setStyleSheet("background-color: rgb(224, 255, 220);")
        self.PBL.setDefault(False)
        self.PBL.setFlat(False)
        self.PBL.setObjectName("PBL")
        self.LDelay = QtWidgets.QLabel(self.widget)
        self.LDelay.setGeometry(QtCore.QRect(10, 460, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LDelay.setFont(font)
        self.LDelay.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                                  "color: rgb(224, 255, 220);")
        self.LDelay.setObjectName("LDelay")
        self.SDelay = QtWidgets.QSpinBox(self.widget)
        self.SDelay.setGeometry(QtCore.QRect(106, 460, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.SDelay.setFont(font)
        self.SDelay.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                                  "color: rgb(224, 255, 220);")
        self.SDelay.setObjectName("SDelay")
        self.LNV = QtWidgets.QLabel(self.widget)
        self.LNV.setGeometry(QtCore.QRect(20, 190, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LNV.setFont(font)
        self.LNV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LNV.setObjectName("LNV")
        self.LTH = QtWidgets.QLabel(self.widget)
        self.LTH.setGeometry(QtCore.QRect(20, 220, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LTH.setFont(font)
        self.LTH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LTH.setObjectName("LTH")
        self.NH = QtWidgets.QLineEdit(self.widget)
        self.NH.setGeometry(QtCore.QRect(240, 160, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.NH.setFont(font)
        self.NH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.NH.setObjectName("NH")
        self.LRV = QtWidgets.QLabel(self.widget)
        self.LRV.setGeometry(QtCore.QRect(20, 310, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LRV.setFont(font)
        self.LRV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LRV.setObjectName("LRV")
        self.TH = QtWidgets.QLineEdit(self.widget)
        self.TH.setGeometry(QtCore.QRect(240, 220, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.TH.setFont(font)
        self.TH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.TH.setObjectName("TH")
        self.NV = QtWidgets.QLineEdit(self.widget)
        self.NV.setGeometry(QtCore.QRect(240, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.NV.setFont(font)
        self.NV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.NV.setObjectName("NV")
        self.LRH = QtWidgets.QLabel(self.widget)
        self.LRH.setGeometry(QtCore.QRect(20, 280, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LRH.setFont(font)
        self.LRH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LRH.setObjectName("LRH")
        self.HH = QtWidgets.QLineEdit(self.widget)
        self.HH.setGeometry(QtCore.QRect(240, 340, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.HH.setFont(font)
        self.HH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.HH.setObjectName("HH")
        self.TV = QtWidgets.QLineEdit(self.widget)
        self.TV.setGeometry(QtCore.QRect(240, 250, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.TV.setFont(font)
        self.TV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.TV.setObjectName("TV")
        self.RV = QtWidgets.QLineEdit(self.widget)
        self.RV.setGeometry(QtCore.QRect(240, 310, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.RV.setFont(font)
        self.RV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.RV.setObjectName("RV")
        self.LNH = QtWidgets.QLabel(self.widget)
        self.LNH.setGeometry(QtCore.QRect(20, 160, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LNH.setFont(font)
        self.LNH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LNH.setObjectName("LNH")
        self.LHH = QtWidgets.QLabel(self.widget)
        self.LHH.setGeometry(QtCore.QRect(20, 340, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LHH.setFont(font)
        self.LHH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LHH.setObjectName("LHH")
        self.RH = QtWidgets.QLineEdit(self.widget)
        self.RH.setGeometry(QtCore.QRect(240, 280, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.RH.setFont(font)
        self.RH.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.RH.setObjectName("RH")
        self.LTV = QtWidgets.QLabel(self.widget)
        self.LTV.setGeometry(QtCore.QRect(20, 250, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LTV.setFont(font)
        self.LTV.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                               "color: rgb(224, 255, 220);")
        self.LTV.setObjectName("LTV")
        self.PBHJ = QtWidgets.QPushButton(self.widget)
        self.PBHJ.setGeometry(QtCore.QRect(10, 120, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.PBHJ.setFont(font)
        self.PBHJ.setStyleSheet("background-color: rgb(224, 255, 220);")
        self.PBHJ.setObjectName("PBHJ")
        self.PBE = QtWidgets.QPushButton(self.widget)
        self.PBE.setGeometry(QtCore.QRect(10, 380, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.PBE.setFont(font)
        self.PBE.setStyleSheet("background-color: rgb(224, 255, 220);")
        self.PBE.setObjectName("PBE")
        self.PBD = QtWidgets.QPushButton(self.widget)
        self.PBD.setGeometry(QtCore.QRect(10, 420, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.PBD.setFont(font)
        self.PBD.setStyleSheet("background-color: rgb(224, 255, 220);")
        self.PBD.setObjectName("PBD")
        self.LSize = QtWidgets.QLabel(self.widget)
        self.LSize.setGeometry(QtCore.QRect(155, 460, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.LSize.setFont(font)
        self.LSize.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                                 "color: rgb(224, 255, 220);")
        self.LSize.setObjectName("LSize")
        self.CS = QtWidgets.QLineEdit(self.widget)
        self.CS.setGeometry(QtCore.QRect(280, 460, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.CS.setFont(font)
        self.CS.setStyleSheet("background-color: rgba(243, 255, 7, 0);\n"
                              "color: rgb(224, 255, 220);")
        self.CS.setObjectName("CS")
        Title.setCentralWidget(self.centralwidget)

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "Выбор модели"))
        self.CRule.setItemText(0, _translate("Title", "B3/S2,3"))
        self.CRandom.setText(_translate("Title", "Заполнить случайным образом"))
        self.LRule.setText(_translate("Title", "Используемое правило:"))
        self.PBL.setText(_translate("Title", "Игра \"Жизнь\""))
        self.LDelay.setText(_translate("Title", "Задержка (мс):"))
        self.LNV.setText(_translate("Title", "Количество жертв"))
        self.LTH.setText(_translate("Title", "Период размножения хищников"))
        self.NH.setText(_translate("Title", "100"))
        self.LRV.setText(_translate("Title", "Радиус зрения жертв"))
        self.TH.setText(_translate("Title", "10"))
        self.NV.setText(_translate("Title", "500"))
        self.LRH.setText(_translate("Title", "Радиус зрения хищников"))
        self.HH.setText(_translate("Title", "15"))
        self.TV.setText(_translate("Title", "10"))
        self.RV.setText(_translate("Title", "3"))
        self.LNH.setText(_translate("Title", "Количество хищников"))
        self.LHH.setText(_translate("Title", "Время голодного существования"))
        self.RH.setText(_translate("Title", "15"))
        self.LTV.setText(_translate("Title", "Период размножения жертв"))
        self.PBHJ.setText(_translate("Title", "Хищник-жертва"))
        self.PBE.setText(_translate("Title", "Экосистема"))
        self.PBD.setText(_translate("Title", "Диффузия"))
        self.LSize.setText(_translate("Title", "Размер клетки (пк):"))
        self.CS.setText(_translate("Title", "10"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Title = QtWidgets.QMainWindow()
    ui = Ui_Title()
    ui.setupUi(Title)
    Title.show()
    sys.exit(app.exec_())
